### ISSUE TITLE
AbstractGraph refactor

### ISSUE THREAD

**Issue by f-aguzzi** [ScrapeGraphAI/Scrapegraph-ai#497]
**Is your feature request related to a problem? Please describe.**
The code:
- is messy (long module, irregular implementation)
- has known bugs (some custom embeddings do not work even if implemented, see #496)
- is hard to read (irregular formatting)
- is difficult to understand for newcomers and contributors

**Describe the solution you'd like**
Ideally, the module should be rewritten from scratch at some point. In the meanwhile, all dead code should be removed (for example, the RAG node has been deprecated in all graphs, so the sections about embeddings have become useless).
A better use of LangChain and of its latest features should remove some of the complexity.

**Describe alternatives you've considered**
Possible alternatives will be considered and explained in the follow-ups to this issue.

**Comment by f-aguzzi** [comment]
The main tasks are:
- [ ] clean up the code and enforce correct formatting
- [ ] remove dead imports
- [ ] transplant the embedding initialization blocks into the `RAGNode`

**Comment by f-aguzzi** [comment]
The process should fix the following issues too:
- [ ] #413 (`batch_size` kwarg)
- [ ] #496 (Gemini embeddings not matching pattern)
- [ ] #460 (choice of custom embeddings)

**Comment by f-aguzzi** [comment]
Also this:
- [ ] #501 (Azure-hosted GPT models get incorrectly treated as OpenAI)
